src/LJD.App.Web/Areas/Admin/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using LJD.App.Model.DbModels;
using LJD.App.Repository.IUnitOfWork;
using LJD.App.Service;
using LJD.App.Service.IService;
using LJD.App.Util;
using LJD.App.Web.Controllers;
using Microsoft.AspNetCore.Mvc;

namespace LJD.App.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserInfoController : BaseController
    {
        private readonly ISysUserInfoService _sysUserInfoService;
        private readonly ISysRoleService _sysRoleService;
        private readonly IR_sysUserInfo_sysRoleService _sysUserInfoSysRoleService; 
        private readonly IUnitOfWork _unitOfWork;

        public UserInfoController(ISysUserInfoService sysUserInfoService,ISysRoleService sysRoleService,IR_sysUserInfo_sysRoleService sysUserInfoSysRoleService,IUnitOfWork unitOfWork)
        {
            _sysUserInfoService = sysUserInfoService;
            _sysRoleService = sysRoleService;
            _sysUserInfoSysRoleService = sysUserInfoSysRoleService; 
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(string uloginName,string urealName,string ugender,string status,PagerInfo pagerInfo)
        {
            Expression<Func<SysUserInfo, bool>> whereExpression = u => true;
            if (!string.IsNullOrEmpty(uloginName))
            {
                whereExpression= whereExpression.And(u => u.ULoginName.Contains(uloginName));
            }
            if (!string.IsNullOrEmpty(urealName))
            {
                whereExpression = whereExpression.And(u => u.URealName.Contains(urealName));
            }
            if (!string.IsNullOrEmpty(ugender))
            {
                int gender = Convert.ToInt32(ugender);
                whereExpression = whereExpression.And(u => u.UGender.Equals(gender));
            }
            if (!string.IsNullOrEmpty(status))
            {
                int state = Convert.ToInt32(status);
                whereExpression = whereExpression.And(u => u.Status.Equals(state));
            }

            var list = _sysUserInfoService.GetList(pagerInfo.PageIndex, pagerInfo.PageSize, out var count, whereExpression, false, u => u.CreatedTime);

            return Json(BuildSuccessTableResult(count, list));
        }

        public IActionResult Form(string objectId)
        {
            //如果objectId不为空的话 需要则是编辑，获取信息否则新建一个
            var sysUserInfo = string.IsNullOrEmpty(objectId)?new SysUserInfo() { Status = (int)Status.On } : _sysUserInfoService.GetList(u => u.ObjectID.Equals(objectId)).FirstOrDefault(); 

            return View(sysUserInfo);
        }

        [HttpPost]
        public IActionResult Form(SysUserInfo sysUserInfo)
        {
            ResponseResult responseResult = new ResponseResult(success:false,message:"保存失败！");
            if (string.IsNullOrEmpty(sysUserInfo.ObjectID))
            {
                sysUserInfo.CreatedBy = CurrentUserManage.UserInfo.URealName;
                sysUserInfo.CreatedTime = DateTime.Now;
                sysUserInfo.ULoginPWD = GlobalSwitch.InitialPassword.ToMD5String();
                sysUserInfo.Status = sysUserInfo.Status == 0 ? 0 : 1;
                _sysUserInfoService.Create(sysUserInfo); 
            }
            else
            {
                var sysUser = _sysUserInfoService.GetList(u => u.ObjectID.Equals(sysUserInfo.ObjectID))
                    .FirstOrDefault();
                if (sysUser != null)
                { 
                    sysUser.URealName = sysUserInfo.URealName;
                    sysUser.UTelphone = sysUserInfo.UTelphone;
                    sysUser.UMobile = sysUserInfo.UMobile;
                    sysUser.UEmail = sysUserInfo.UEmail;
                    sysUser.UQQ = sysUserInfo.UQQ;
                    sysUser.UGender = sysUserInfo.UGender;
                    sysUser.UDepID = sysUserInfo.UDepID;
                    sysUser.Remark = sysUserInfo.Remark;
                    sysUser.Status = sysUserInfo.Status==0?0:1;
                    sysUser.ModifiedTime=DateTime.Now;
                    sysUser.ModifiedBy = CurrentUserManage.UserInfo.URealName;
                    _sysUserInfoService.Edit(sysUser);
                }
            }

            if (_unitOfWork.SaveChanges()==1)
            {
                responseResult.Success = true;
                responseResult.Message = "保存成功！";
            }

            return Json(responseResult);

        }

        [HttpPost]
        public IActionResult Delete(string ids)
        {
            var idsList = ids.ToList<string>();
            _sysUserInfoService.Delete(u=>idsList.Contains(u.ObjectID));
            _unitOfWork.SaveChanges();
            return Json(new ResponseResult(true, "删除成功！"));

        }

        public IActionResult SetRole(string userId)
        {
            ViewData["userId"] = userId;
            //1.获取该用户已经拥有的权限
            ViewData["roleList"] = _sysUserInfoSysRoleService.GetList(r => r.UserInfoID.Equals(userId))
                .Select(r => r.RoleID).ToList();
            //2.搜索所有的角色  禁用的前端控制不可选
            var roleList = _sysRoleService.GetList(r => true).OrderBy(r => r.Sort).ToList();
            return View(roleList);
        }
        [HttpPost]
        public IActionResult SetRole(string userId, string roles)
        {
            List<string> roleList = roles.ToList<string>();
            ResponseResult responseResult = new ResponseResult(false);

            try
            {
                //1.先删除该用户的所有角色
                _sysUserInfoSysRoleService.Delete(r=>r.UserInfoID.Equals(userId));
                //2.循环 roleList 
                foreach (string role in roleList)
                {
                     
                    R_sysUserInfo_sysRole sysUserInfoSysRole = new R_sysUserInfo_sysRole()
                    {
                        UserInfoID = userId,
                        RoleID = role
                    };

                    _sysUserInfoSysRoleService.Create(sysUserInfoSysRole);
                }

                responseResult.Message = "保存成功!";
                responseResult.Success = true;
                _unitOfWork.SaveChanges();
                //todo:3.清缓存
            }
            catch (Exception ex)
            {
                responseResult.Message = ex.Message;
                throw;
            }
            return Json(responseResult);

        }
    }
}

src/LJD.App.Web/Areas/Admin/Views/UserInfo/Form.cshtml
@using LJD.App.Util
@model LJD.App.Model.DbModels.SysUserInfo

@{
    ViewData["Title"] = "编辑";
    Layout = "~/Views/Shared/_LayUIFormLayout.cshtml";
}

<div class="layui-form" lay-filter="layuiadmin-app-form-list" id="layuiadmin-app-form-list" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item layui-hide layui-col-md12">
        <label class="layui-form-label">ObjectId</label>
        <div class="layui-input-inline">
            <input type="text" name="ObjectID" placeholder="ObjectId" value="@Model.ObjectID" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">用户名</label>
        <div class="layui-input-block">
            <input type="text" name="ULoginName" lay-verify="ULoginName" value="@Model.ULoginName" placeholder="请输入用户名" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">真实姓名</label>
        <div class="layui-input-block">
            <input type="text" name="URealName" lay-verify="URealName" value="@Model.URealName" placeholder="请输入真实姓名" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">电话</label>
        <div class="layui-input-block">
            <input type="text" name="UTelphone" lay-verify="UTelphone" value="@Model.UTelphone" placeholder="请输入电话" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">手机号</label>
        <div class="layui-input-block">
            <input type="text" name="UMobile" lay-verify="required|phone" value="@Model.UMobile" placeholder="请输入手机号" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">Email</label>
        <div class="layui-input-block">
            <input type="text" name="UEmail" lay-verify="email" value="@Model.UEmail" placeholder="请输入Email" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">QQ</label>
        <div class="layui-input-block">
            <input type="text" name="UQQ" lay-verify="UQQ" value="@Model.UQQ" placeholder="请输入QQ" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">性别</label>
        <div class="layui-input-block">
            @{
                if (Model.UGender.Equals((int)Gender.Man))
                {
                    <input type="radio" name="UGender" value="1" title="男" checked>
                    <input type="radio" name="UGender" value="0" title="女"> 
                }
                else
                {
                    <input type="radio" name="UGender" value="1" title="男">
                    <input type="radio" name="UGender" value="0" title="女" checked> 
                }
            }

        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">所属部门</label>
        <div class="layui-input-block">
            <select name="UDepID" lay-verify="required" lay-search>
                <option value="">带搜索的选择框</option>
                <option value="1">layer</option>
                <option value="2">form</option>
                <option value="3">layim</option>
            </select>
        </div>
    </div>

    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <textarea name="Remark" lay-verify="required" autocomplete="off" class="layui-textarea">@Model.Remark</textarea>
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">状态</label>
        <div class="layui-input-block">
            @if (Model.Status.Equals((int)Status.On))
            {
                <input type="checkbox" lay-filter="status" value="0" name="Status" lay-skin="switch" lay-text="启用|禁用" checked>
            }
            else
            {
                <input type="checkbox" lay-filter="status" value="0" name="Status" lay-skin="switch" lay-text="启用|禁用">
            }
        </div>
    </div>
    <div class="layui-form-item layui-hide">
        <input type="button" lay-submit lay-filter="layuiadmin-app-form-submit" id="layuiadmin-app-form-submit" value="确认添加">
        <input type="button" lay-submit lay-filter="layuiadmin-app-form-edit" id="layuiadmin-app-form-edit" value="确认编辑">
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
        layui.use(['form'],
            function() {
                var $ = layui.$, form = layui.form; 
                //监听提交
                form.on('submit(layuiadmin-app-form-submit)',
                    //注意：这里只是添加的用，编辑的在index页面
                    function(data) {
                        var field = data.field; //获取提交的字段 
                        var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                        debugger;
                        //提交 Ajax 成功后，关闭当前弹层并重载表格
                        $.ajax({
                            url: '@Url.Action("Form", "UserInfo")',
                            type: 'POST',
                            data: field,
                            dataType: 'json',
                            success: function(data) {
                                debugger;
                                if (data.Success) {
                                    parent.layui.table.reload('LAY-app-list'); //重载表格
                                    parent.layer.close(index); //再执行关闭
                                } else {
                                    layer.msg(data.Message, {icon: 5});
                                }
                            }
                        });
                    });
                /* 自定义验证规则 */
                form.verify({
                    ULoginName: function(value) {
                        if (value.length < 5||value.length>15||!/^[A-Za-z0-9]+$/.test(value)) {
                            return '用户名必须由英文或数字组成且长度为5-15';
                        }
                    },
                    URealName: function(value) {
                        if (value.length < 2) {
                            return '姓名至少2个汉字';
                        }
                        if (!/^[\u4e00-\u9fa5]{0,}$/.test(value)) {
                            return '姓名必须是汉字';
                        }
                    },
                    UTelphone: [/\d{3}-\d{8}|\d{4}-\d{7,8}/, '请输入正确的电话号码'],
                    Uqq: [/[1-9][0-9]{4,}/, '请输入正确的QQ号']

                });
            })
    </script>
}

src/LJD.App.Web/Areas/Admin/Views/UserInfo/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayUILayout.cshtml";
}

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline ">
                    <label class="layui-form-label">用户名</label>
                    <div class="layui-input-inline">
                        <input type="text" name="uloginName" placeholder="请输入" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">真实姓名</label>
                    <div class="layui-input-inline">
                        <input type="text" name="urealName" placeholder="请输入" autocomplete="off" class="layui-input">
                    </div>
                </div> 
                <div class="layui-inline">
                    <label class="layui-form-label">性别</label>
                    <div class="layui-input-inline">
                        <select name="ugender">
                            <option value="">请选择</option>
                            <option value="1">男</option>
                            <option value="0">女</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-inline">
                        <select name="status">
                            <option value="">请选择</option>
                            <option value="0">启用</option>
                            <option value="1">禁用</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layuiadmin-btn-list" lay-submit lay-filter="LAY-app-search">
                        <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                    </button>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <button class="layui-btn layuiadmin-btn-list" data-type="add">添加</button>
                <button class="layui-btn layuiadmin-btn-list" data-type="setRole">分配角色</button>
                <button class="layui-btn layuiadmin-btn-list" data-type="batchdel">删除</button>
            </div>
            <table id="LAY-app-list" lay-filter="LAY-app-list"></table>
            <script type="text/html" id="StatusTpl">
                {{#  if(d.Status==0){ }}
                <button class="layui-btn layui-btn-xs">启用</button>
                {{#  } else { }}
                <button class="layui-btn layui-btn-primary layui-btn-xs">禁用</button>
                {{#  } }}
            </script>
            <script type="text/html" id="GenderTpl">
                {{#  if(d.UGender==0){ }}
                <i class="layui-icon layui-icon-female" style="color: #FF5722;font-weight: bold" title="女"></i>
                {{#  } else { }}
                <i class="layui-icon layui-icon-male" style="color: #1E9FFF;font-weight: bold" title="男"></i>
                {{#  } }}
            </script> 
            <script type="text/html" id="table-list">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
        layui.use(['form', 'table'],
            function () {
             var table = layui.table
             ,util=layui.util
            , form = layui.form;
        //Table定义
        table.render({
            elem: "#LAY-app-list",
            url: "@Url.Action("List","UserInfo")"
            ,request: {
                pageName: 'pageIndex' //页码的参数名称，默认：page
                ,limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,cols: [[
                { type: "checkbox", fixed: "left" }
                , { field: "ULoginName", width: 150, title: "用户名" }
                , { field: "URealName", title: "真实姓名", minWidth: 100 }
                , { field: "UTelphone", title: "电话" }
                , { field: "UMobile", title: "手机号" }
                , { field: "UEmail", title: "Email",minWidth:200 }
                , { field: "UQQ", title: "QQ" }
                , { field: "UGender", title: "性别" , templet: "#GenderTpl", width:60, align: "center"}
                , { field: "UDepID", title: "所属部门" }
                , { field: "CreatedTime", title: "创建时间", templet: function (d) {return util.toDateString(d.CreatedTime,"yyyy-MM-dd")} , sort: !0 }
                , { field: "Remark", title: "备注" }
                , { field: "Status", title: "状态", templet: "#StatusTpl", width: 80, align: "center" }
                , { title: "操作", minWidth: 150, align: "center", fixed: "right", toolbar: "#table-list" }
            ]]
            , page: true
            ,limit: 10
            ,limits: [10, 15, 20, 25, 30]
        });
        //监听工具条
        table.on("tool(LAY-app-list)", function (t) {
            var data = t.data;
            if (t.event === "del") {
                layer.confirm("确定删除此记录？", function (e) {
                    var ids = [];
                    ids.push(data.ObjectID);
                    $.ajax({
                        url: '@Url.Action("Delete", "UserInfo")',
                        type: 'POST',
                        data: { ids:  JSON.stringify(ids)},
                        dataType: 'json',
                        success: function(data) {
                            debugger;
                            if (data.Success) { 
                                //表格删除
                                t.del();
                                //关闭弹窗
                                layer.close(e);
                            } else {
                                layer.msg(data.Message, {icon: 5});
                            }
                        }
                    });
                });
            } else if (t.event === "edit") {
                layer.open({
                    type: 2,
                    title: "编辑",
                    content: "@Url.Action("Form","UserInfo")?objectId=" + data.ObjectID,
                    maxmin: !0,
                    area: ['60%', '95%'],
                    btn: ["确定", "取消"],
                    yes: function (e, i) {
                        var l = window["layui-layer-iframe" + e],
                            a = i.find("iframe").contents().find("#layuiadmin-app-form-edit");
                        l.layui.form.on("submit(layuiadmin-app-form-edit)",
                            function (i) {
                                debugger
                                //获取新开窗口的form
                                var field = i.field;

                                //提交 Ajax 成功后，关闭当前弹层并重载表格
                                $.ajax({
                                    url: '@Url.Action("Form", "UserInfo")',
                                    type: 'POST',
                                    data: field,
                                    dataType: 'json',
                                    success: function(data) {
                                        debugger;
                                        if (data.Success) {

                                            //更新表格记录
                                            t.update({ 
                                                URealName: field.URealName,
                                                UTelphone: field.UTelphone,
                                                UMobile: field.UMobile,
                                                UEmail: field.UEmail,
                                                UQQ: field.UQQ,
                                                UGender: field.UGender,
                                                UDepID: field.UDepID,
                                                Remark: field.Remark,
                                                Status: field.Status
                                            });
                                            //清空form
                                            form.render();
                                            //关闭弹窗
                                            layer.close(e);
                                        } else {
                                            layer.msg(data.Message, {icon: 5});
                                        }
                                    }
                                });
                            }), a.trigger("click");
                    }
                });
            }
        });

        //监听搜索
        form.on('submit(LAY-app-search)', function (data) {
            var field = data.field;

            //执行重载
            table.reload('LAY-app-list', {
                where: field
            });
        });
        //顶部按钮
        var $ = layui.$, active = {
            batchdel: function () {
                var checkStatus = table.checkStatus('LAY-app-list')
                    , checkData = checkStatus.data; //得到选中的数据

                if (checkData.length === 0) {
                    return layer.msg('请选择数据');
                }
                layer.confirm('确定删除吗？', function (index) {
                    var ids = [];
                    $.each(checkData,
                        function(index, value) {
                            ids.push(value['ObjectID']);
                        }); 
                    //执行 Ajax 后重载
                    $.ajax({
                        url: '@Url.Action("Delete", "UserInfo")',
                        type: 'POST',
                        data: { ids: JSON.stringify(ids) },
                        dataType: 'json',
                        success: function(data) {
                            debugger;
                            if (data.Success) {
                                table.reload('LAY-app-list');
                                layer.msg(data.Message, {icon: 6});
                            } else {
                                layer.msg(data.Message, {icon: 5});
                            }
                        }
                    });
                }); 
            },
            add: function () {
                layer.open({
                    type: 2
                    , title: '添加'
                    , content: '@Url.Action("Form","UserInfo")'
                    , maxmin: true
                    , area: ['60%', '95%']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        //点击确认触发 iframe 内容中的按钮提交
                        var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                        submit.click();
                    }
                });
            },
            setRole: function() {
                var checkStatus = table.checkStatus('LAY-app-list')
                    , checkData = checkStatus.data; //得到选中的数据

                if (checkData.length !== 1) {
                    return layer.msg("只能选择一个用户分配角色!", {icon: 5});
                }
                debugger
                var user = checkData[0];
                layer.open({
                    type: 2
                    , title: '【'+user.URealName+'】分配角色'
                    , content: '@Url.Action("SetRole","UserInfo")?userId='+user.ObjectID
                    , maxmin: true
                    , area: ['60%', '95%']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        //点击确认触发 iframe 内容中的按钮提交
                        var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                        submit.click();
                    }
                }); 
            } 
        };

        $('.layui-btn.layuiadmin-btn-list').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
    </script>
}

src/LJD.App.Web/Areas/Admin/Views/UserInfo/SetRole.cshtml
@using LJD.App.Model.DbModels
@using LJD.App.Util
@model List<LJD.App.Model.DbModels.SysRole>
@{
    List<string> roleList = (List<string>)ViewData["roleList"];
}

@{
    ViewData["Title"] = "SetRole";
    Layout = "~/Views/Shared/_LayUIFormLayout.cshtml";
}
<div class="layui-form" lay-filter="layuiadmin-app-form-list" id="layuiadmin-app-form-list" style="padding: 20px">
    @{
        foreach (SysRole sysRole in Model)
        {
        <input type="checkbox" value="@sysRole.ObjectID" title="@sysRole.RName" @(roleList.Contains(sysRole.ObjectID) ? "checked" : "")  @(sysRole.Status.Equals((int)Status.Off)?"disabled":"")>
        }
    }
    <div class="layui-form-item layui-hide">
        <input type="button" lay-submit lay-filter="layuiadmin-app-form-submit" id="layuiadmin-app-form-submit" value="确认添加">
        <input type="button" lay-submit lay-filter="layuiadmin-app-form-edit" id="layuiadmin-app-form-edit" value="确认编辑">
    </div>
</div>

@section scripts
    {
    <script type="text/javascript">
        layui.use(['form'],
            function () {
                var $ = layui.$, form = layui.form;
                form.on('submit(layuiadmin-app-form-submit)',
                    function(data) {
                        //获取选中的权限项
                        var roles = [];
                        $('input:checked').each(function (index, item) {
                            roles.push($(item).attr('value'));
                        });

                        //layer.alert(JSON.stringify(roles));
                        var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                        debugger;
                        //提交 Ajax 成功后，关闭当前弹层并重载表格
                        $.ajax({
                            url: '@Url.Action("SetRole", "UserInfo")',
                            type: 'POST',
                            data: {userId:'@ViewData["userId"].ToString()',roles:JSON.stringify(roles)},
                            dataType: 'json',
                            success: function (data) {
                                debugger;
                                if (data.Success) {
                                    parent.layui.table.reload('LAY-app-list'); //重载表格
                                    parent.layer.close(index); //再执行关闭
                                } else {
                                    layer.msg(data.Message, {icon: 5});
                                }
                            }
                        });
                    });
            });
    </script>
}