src/LJD.App.Web/Areas/Admin/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Linq.Expressions;
using LJD.App.Model.DbModels;
using LJD.App.Repository.IUnitOfWork;
using LJD.App.Service;
using LJD.App.Service.IService;
using LJD.App.Util;
using LJD.App.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LJD.App.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : BaseController
    {
        private readonly ISysRoleService _sysRoleService;
        private readonly ISysMenusService _sysMenusService;
        private readonly IUnitOfWork _unitOfWork;

        public RoleController(ISysRoleService sysRoleService,ISysMenusService sysMenusService, IUnitOfWork unitOfWork)
        {
            _sysRoleService = sysRoleService;
            _sysMenusService = sysMenusService;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(string rName,string status,PagerInfo pagerInfo)
        {
            Expression<Func<SysRole, bool>> whereExpression = r => true;
            if (!string.IsNullOrEmpty(rName))
            {
                whereExpression = whereExpression.And(r => r.RName.Contains(rName));
            }
            if (!string.IsNullOrEmpty(status))
            {
                int state = Convert.ToInt32(status);
                whereExpression = whereExpression.And(r => r.Status.Equals(state));
            }

            var list = _sysRoleService.GetList(pagerInfo.PageIndex, pagerInfo.PageSize, out var count, whereExpression, true, r => r.Sort);

            return Json(BuildSuccessTableResult(count, list));
        }

        public IActionResult Form(string objectId)
        {
            //如果objectId不为空的话 需要则是编辑，获取信息否则新建一个
            var sysRole = string.IsNullOrEmpty(objectId) ? new SysRole() { Status = (int)Status.On } : _sysRoleService.GetList(r => r.ObjectID.Equals(objectId)).FirstOrDefault();

            return View(sysRole);
        }

        [HttpPost]
        public IActionResult Form(SysRole sysRole)
        {
            ResponseResult responseResult = new ResponseResult(success: false, message: "保存失败！");
            if (string.IsNullOrEmpty(sysRole.ObjectID))
            {
                sysRole.CreatedBy = CurrentUserManage.UserInfo.URealName;
                sysRole.CreatedTime = DateTime.Now;
                sysRole.Status = sysRole.Status == 0 ? 0 : 1;
                _sysRoleService.Create(sysRole);

                if (_unitOfWork.SaveChanges() == 1)
                {
                    responseResult.Success = true;
                    responseResult.Message = "保存成功！";
                }
            }
            else
            {
                var model = _sysRoleService.GetList(r => r.ObjectID.Equals(sysRole.ObjectID))
                    .FirstOrDefault();
                if (model != null)
                {

                    model.RName = sysRole.RName;
                    model.Remark = sysRole.Remark;
                    model.Sort = sysRole.Sort;
                    //后台设置项
                    model.Status = sysRole.Status == 0 ? 0 : 1;
                    model.ModifiedTime = DateTime.Now;
                    model.ModifiedBy = CurrentUserManage.UserInfo.URealName;
                    _sysRoleService.Edit(model);


                    if (_unitOfWork.SaveChanges() == 1)
                    {
                        responseResult.Success = true;
                        responseResult.Message = "保存成功！";
                    }
                }
                else
                {
                    responseResult.Message = "要修改的数据不存在！";
                }
            }

            return Json(responseResult);

        }

        [HttpPost]
        public IActionResult Delete(string ids)
        {
            var idsList = ids.ToList<string>();
            _sysRoleService.Delete(r => idsList.Contains(r.ObjectID));
            _unitOfWork.SaveChanges();
            return Json(new ResponseResult(true, "删除成功！"));

        }

        public IActionResult SetPermission(string roleObjectId,string rName)
        {
            ViewData["roleObjectId"] = roleObjectId;
            ViewData["rName"] = rName;
            //获取角色已有权限项ID
            ViewData["permissionList"] = PermissionManage.GetPermissionByRole(roleObjectId);
            //获取所有菜单   禁用的前端进行了控制
            var menus = _sysMenusService.GetList(m => true).Include("SysFunction").OrderBy(m => m.Hierarchy).ThenBy(m=>m.Sort).ToList();

            return View(menus);
        }
        /// <summary>
        /// 设置权限  怎加tag 是为区分，设置权限的时候好配置
        /// </summary>
        /// <param name="roleObjectId"></param>
        /// <param name="permissions"></param>
        /// <param name="tag"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult SetPermission(string roleObjectId,string permissions,string tag)
        {
           var res= PermissionManage.SetPermissionWithRole(roleObjectId, permissions.ToList<string>());
            return Json(res);
        }
    }
}

src/LJD.App.Web/Areas/Admin/Views/Role/BuildPermissionMenu.cshtml
@using LJD.App.Model.DbModels
@using LJD.App.Util

@model List<SysMenus>
@{
    List<string> permissionList = (List<string>)ViewData["permissionList"];
    int on = (int) Status.On;
}

@foreach (SysMenus menu in Model.Where(m => m.ParentID.Equals(ViewData["ParentID"].ToString())&&m.Status.Equals(on)).OrderBy(m => m.Sort))
{

    if (menu.IsLast.Equals(on))
    {
<div class="layui-form-item">
    <label class="layui-form-label">@menu.MName：</label>
    <div class="layui-input-block">
        @foreach (SysFunction sysFunction in menu.SysFunction.OrderBy(f => f.Sort))
                {
                    if (sysFunction.Status.Equals(on))
                    {
        <input type="checkbox" isLast="true" value="@menu.ObjectID=@sysFunction.ObjectID" name="@sysFunction.FFunction" title="@sysFunction.FName" parentId="@menu.ParentID" lay-skin="primary" @(permissionList.Contains(sysFunction.ObjectID) ? "checked" : "")>
                    }
                    else
                    {
        <button class="layui-btn layui-btn-xs layui-btn-disabled">@sysFunction.FName</button>

                    }
                }
    </div>
</div>
    }
    else
    {
<div class="layui-card-body">
    <fieldset class="layui-elem-field">
        <legend>
            <input type="checkbox" isLast="false" id="@menu.ObjectID" parentId="@menu.ParentID" value="@menu.ObjectID=@menu.ObjectID" title="@menu.MName" @(permissionList.Contains(menu.ObjectID) ? "checked" : "")>
            @foreach (SysFunction sysFunction in menu.SysFunction.OrderBy(f => f.Sort))
                    {
                        if (sysFunction.Status.Equals(on))
                        {
            <input type="checkbox" isLast="true" value="@menu.ObjectID=@sysFunction.ObjectID"   title="@sysFunction.FName"  lay-skin="primary" @(permissionList.Contains(sysFunction.ObjectID) ? "checked" : "")>
                        }
                        else
                        {
            <button class="layui-btn layui-btn-xs layui-btn-disabled">@sysFunction.FName</button>

                        }
                    }

        </legend>
        <div class="layui-field-box">

            @{ViewData["ParentID"] = menu.ObjectID;}
            @Html.Partial("BuildPermissionMenu", Model, ViewData)
        </div>
    </fieldset>
</div>
    }
}

src/LJD.App.Web/Areas/Admin/Views/Role/Form.cshtml
@using LJD.App.Util
@model LJD.App.Model.DbModels.SysRole

@{
    ViewData["Title"] = "编辑";
    Layout = "~/Views/Shared/_LayUIFormLayout.cshtml";
}

<div class="layui-form" lay-filter="layuiadmin-app-form-list" id="layuiadmin-app-form-list" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item layui-hide layui-col-md12">
        <label class="layui-form-label">ObjectId</label>
        <div class="layui-input-inline">
            <input type="text" name="ObjectID" placeholder="ObjectId" value="@Model.ObjectID" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">角色名称</label>
        <div class="layui-input-block">
            <input type="text" name="RName" value="@Model.RName" placeholder="请输入角色名称" autocomplete="off" class="layui-input">
        </div>
    </div>
      
    <div class="layui-form-item layui-col-md12">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <textarea name="Remark" lay-verify="required" autocomplete="off" class="layui-textarea">@Model.Remark</textarea>
        </div>
    </div>
    <div class="layui-form-item layui-col-md12">
        <div class="layui-col-md6">
            <label class="layui-form-label">状态</label>
            <div class="layui-input-inline">
                @if (Model.Status.Equals((int) Status.On))
                {
                    <input type="checkbox" lay-filter="status" value="0" name="Status" lay-skin="switch" lay-text="启用|禁用" checked>
                }
                else
                {
                    <input type="checkbox" lay-filter="status" value="0" name="Status" lay-skin="switch" lay-text="启用|禁用">
                }
            </div>
        </div>
        <div class="layui-col-md6">
            <label class="layui-form-label">排序值</label>
            <div class="layui-input-inline">
                <input type="number" name="Sort" value="@Model.Sort" placeholder="请输入排序值" autocomplete="off" class="layui-input">
            </div>
        </div>
    </div>
    <div class="layui-form-item layui-hide">
        <input type="button" lay-submit lay-filter="layuiadmin-app-form-submit" id="layuiadmin-app-form-submit" value="确认添加">
        <input type="button" lay-submit lay-filter="layuiadmin-app-form-edit" id="layuiadmin-app-form-edit" value="确认编辑">
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
        layui.use(['form'],
            function() {
                var $ = layui.$, form = layui.form;
                //监听提交
                form.on('submit(layuiadmin-app-form-submit)',
                    //注意：这里只是添加的用，编辑的在index页面
                    function(data) {
                        var field = data.field; //获取提交的字段
                        var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                        debugger;
                        //提交 Ajax 成功后，关闭当前弹层并重载表格
                        $.ajax({
                            url: '@Url.Action("Form", "Role")',
                            type: 'POST',
                            data: field,
                            dataType: 'json',
                            success: function(data) {
                                debugger;
                                if (data.Success) {
                                    parent.layui.table.reload('LAY-app-list'); //重载表格
                                    parent.layer.close(index); //再执行关闭
                                } else {
                                    layer.msg(data.Message, {icon: 5});
                                }
                            }
                        });
                    });
                /* 自定义验证规则 */
                form.verify({
                    //ULoginName: function(value) {
                        //if (value.length < 5||value.length>15||!/^[A-Za-z0-9]+$/.test(value)) {
                            //return '用户名必须由英文或数字组成且长度为5-15';
                        //}
                    //},
                    //URealName: function(value) {
                        //if (value.length < 2) {
                            //return '姓名至少2个汉字';
                        //}
                        //if (!/^[\u4e00-\u9fa5]{0,}$/.test(value)) {
                            //return '姓名必须是汉字';
                        //}
                    //},
                    //UTelphone: [/\d{3}-\d{8}|\d{4}-\d{7,8}/, '请输入正确的电话号码'],
                    //Uqq: [/[1-9][0-9]{4,}/, '请输入正确的QQ号']

                });
            })
    </script>
}

src/LJD.App.Web/Areas/Admin/Views/Role/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayUILayout.cshtml";
}

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline ">
                    <label class="layui-form-label">角色名称</label>
                    <div class="layui-input-inline">
                        <input type="text" name="rName" placeholder="请输入" autocomplete="off" class="layui-input">
                    </div>
                </div>

                <div class="layui-inline">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-inline">
                        <select name="status">
                            <option value="">请选择</option>
                            <option value="0">启用</option>
                            <option value="1">禁用</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layuiadmin-btn-list" lay-submit lay-filter="LAY-app-search">
                        <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                    </button>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <button class="layui-btn layuiadmin-btn-list" data-type="batchdel">删除</button>
                <button class="layui-btn layuiadmin-btn-list" data-type="add">添加</button>
            </div>
            <table id="LAY-app-list" lay-filter="LAY-app-list"></table>
            <script type="text/html" id="StatusTpl">
                {{#  if(d.Status==0){ }}
                <button class="layui-btn layui-btn-xs">启用</button>
                {{#  } else { }}
                <button class="layui-btn layui-btn-primary layui-btn-xs">禁用</button>
                {{#  } }}
            </script>
            <script type="text/html" id="table-list">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-bg-orange layui-btn-xs" lay-event="permission"><i class="layui-icon layui-icon-set"></i>分配权限</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
         layui.use(['util','form', 'table'], function () {
             var table = layui.table
             ,util=layui.util
            , form = layui.form;
        //Table定义
        table.render({
            elem: "#LAY-app-list",
            url: "@Url.Action("List","Role")"
            ,request: {
                pageName: 'pageIndex' //页码的参数名称，默认：page
                ,limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,cols: [[
                { type: "checkbox", fixed: "left" }
                , { field: "RName", title: "角色名称" }
                , { field: "Remark", title: "备注" }
                , { field: "Sort", title: "排序值" }
                //通用项
                , { field: "CreatedTime", title: "创建时间", templet: function (d) {return util.toDateString(d.CreatedTime,"yyyy-MM-dd")} , sort: !0 }
                , { field: "Status", title: "状态", templet: "#StatusTpl", width: 80, align: "center" }
                , { title: "操作", minWidth: 150, align: "center", fixed: "right", toolbar: "#table-list" }
            ]]
            , page: true
            ,limit: 10
            ,limits: [10, 15, 20, 25, 30]
        });
        //监听工具条
        table.on("tool(LAY-app-list)", function (t) {
            var data = t.data;
            if (t.event === "del") {
                layer.confirm("确定删除此记录？", function (e) {
                    var ids = [];
                    ids.push(data.ObjectID);
                    $.ajax({
                        url: '@Url.Action("Delete", "Role")',
                        type: 'POST',
                        data: { ids:  JSON.stringify(ids)},
                        dataType: 'json',
                        success: function(data) {
                            debugger;
                            if (data.Success) {
                                //表格删除
                                t.del();
                                //关闭弹窗
                                layer.close(e);
                            } else {
                                layer.msg(data.Message, {icon: 5});
                            }
                        }
                    });
                });
            } else if (t.event === "edit") {
                layer.open({
                    type: 2,
                    title: "编辑",
                    content: "@Url.Action("Form","Role")?objectId=" + data.ObjectID,
                    maxmin: !0,
                    area: ['60%', '95%'],
                    btn: ["确定", "取消"],
                    yes: function (e, i) {
                        var l = window["layui-layer-iframe" + e],
                            a = i.find("iframe").contents().find("#layuiadmin-app-form-edit");
                        l.layui.form.on("submit(layuiadmin-app-form-edit)",
                            function (i) {
                                debugger
                                //获取新开窗口的form
                                var field = i.field;

                                //提交 Ajax 成功后，关闭当前弹层并重载表格
                                $.ajax({
                                    url: '@Url.Action("Form", "Role")',
                                    type: 'POST',
                                    data: field,
                                    dataType: 'json',
                                    success: function(data) {
                                        debugger;
                                        if (data.Success) {

                                            //更新表格记录
                                            t.update({
                                                RName: field.RName,
                                                Remark: field.Remark,
                                                Sort: field.Sort,
                                                Status: field.Status
                                            });
                                            //清空form
                                            form.render();
                                            //关闭弹窗
                                            layer.close(e);
                                        } else {
                                            layer.msg(data.Message, {icon: 5});
                                        }
                                    }
                                });
                            }), a.trigger("click");
                    }
                });
            }else if (t.event==="permission") {
                layer.open({
                    type: 2,
                    title: "设置【"+data.RName+"】权限",
                    content: "@Url.Action("SetPermission","Role")?roleObjectId=" + data.ObjectID+"&rName="+data.RName,
                    maxmin: !0,
                    area: ['60%', '95%'],
                    btn: ["确定", "取消"],
                    yes: function (index, layero) {
                        //点击确认触发 iframe 内容中的按钮提交
                        var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                        submit.click();
                    }
                });
            }
        });

        //监听搜索
        form.on('submit(LAY-app-search)', function (data) {
            var field = data.field;

            //执行重载
            table.reload('LAY-app-list', {
                where: field
            });
        });
        //顶部按钮
        var $ = layui.$, active = {
            batchdel: function () {
                var checkStatus = table.checkStatus('LAY-app-list')
                    , checkData = checkStatus.data; //得到选中的数据

                if (checkData.length === 0) {
                    return layer.msg('请选择数据');
                }
                layer.confirm('确定删除吗？', function (index) {
                    var ids = [];
                    $.each(checkData,
                        function(index, value) {
                            ids.push(value['ObjectID']);
                        });
                    //执行 Ajax 后重载
                    $.ajax({
                        url: '@Url.Action("Delete", "Role")',
                        type: 'POST',
                        data: { ids: JSON.stringify(ids) },
                        dataType: 'json',
                        success: function(data) {
                            debugger;
                            if (data.Success) {
                                table.reload('LAY-app-list');
                                layer.msg(data.Message, {icon: 6});
                            } else {
                                layer.msg(data.Message, {icon: 5});
                            }
                        }
                    });
                });
            },
            add: function () {
                layer.open({
                    type: 2
                    , title: '添加'
                    , content: '@Url.Action("Form","Role")'
                    , maxmin: true
                    , area: ['60%', '95%']
                    , btn: ['确定', '取消']
                    , yes: function (index, layero) {
                        //点击确认触发 iframe 内容中的按钮提交
                        var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                        submit.click();
                    }
                });
            }
        };

        $('.layui-btn.layuiadmin-btn-list').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
    </script>
}