src/LJD.App.Web/Areas/Admin/Controllers/RapidDevelopmentController.cs
using System.Collections.Generic;
using LJD.App.Service.IService;
using LJD.App.Util;
using LJD.App.Web.Controllers;
using Microsoft.AspNetCore.Mvc;

namespace LJD.App.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RapidDevelopmentController : BaseController
    {
        private readonly IRapidDevelopmentService _rapidDevelopmentService;

        public RapidDevelopmentController(IRapidDevelopmentService rapidDevelopmentService)
        {
            _rapidDevelopmentService = rapidDevelopmentService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult List(string tableName, PagerInfo pagerInfo)
        {
            var list = _rapidDevelopmentService.GetDbAllTables(tableName, pagerInfo, out var count);
            return Json(BuildSuccessTableResult(count, list));
        }

        public IActionResult BuildCode(string buildType, string tableName)
        {
            var code = string.Empty;
            var fileName = string.Empty;
            if (buildType.Equals("IRepository"))
            {
                fileName = $"I{tableName}Repository.cs";
                code = BuildIRepositoryCode(tableName);
            }
            else if (buildType.Equals("Repository"))
            {
                fileName = $"{tableName}Repository.cs";
                code = BuildRepositoryCode(tableName);
            }
            else if (buildType.Equals("IService"))
            {
                fileName = $"I{tableName}Service.cs";
                code = BuildIServiceCode(tableName);
            }
            else if (buildType.Equals("Service"))
            {
                fileName = $"{tableName}Service.cs";
                code = BuildServiceCode(tableName);
            }
            ViewData["fileName"] = fileName;
            ViewData["Code"] = code;

            return View();
        }

        private string BuildServiceCode(string tableName)
        {
            var code = $@"using LJD.App.Model.DbModels;
using LJD.App.Repository.IRepository;
using LJD.App.Service.IService;

namespace LJD.App.Service.Service
{{
    private readonly IBaseRepository<SysUser> _iBaseRepository;

    public class {tableName}Service:BaseService<{tableName}>,I{tableName}Service
    {{
        public {tableName}Service(IBaseRepository<{tableName}> iBaseRepository) : base(iBaseRepository)
        {{
            _iBaseRepository = iBaseRepository;
        }}
    }}
}}";
            return code;
        }

        private string BuildIServiceCode(string tableName)
        {
            var code = $@"using LJD.App.Model.DbModels;

namespace LJD.App.Service.IService
{{
    public interface I{tableName}Service:IBaseService<{tableName}>
    {{
        
    }}
}}";
            return code;
        }

        private string BuildIRepositoryCode(string tableName)
        {
            var code = $@"using LJD.App.Model.DbModels;

namespace LJD.App.Repository.IRepository
{{
        public interface I{tableName}Repository:IBaseRepository<{tableName}>
        {{

        }}
}}";
            return code;
        }


        private string BuildRepositoryCode(string tableName)
        {
            var code = $@"using LJD.App.Model.DbModels;
using LJD.App.Repository.IRepository;

namespace LJD.App.Repository.Repository
{{
    public class {tableName}Repository:BaseRepository<{tableName}>,I{tableName}Repository
    {{
        public {tableName}Repository(LJDAPPContext ljdAppContext) : base(ljdAppContext)
        {{
        }}
    }}
}}";
            return code;
        }


        private string BuildModelCode()
        {


            return "using System;\nusing System.Collections.Generic;\nusing Microsoft.EntityFrameworkCore.Metadata.Internal;\n\nnamespace LJD.App.Model.DbModels\n{\n    public partial class SysUser\n    { \n        public int Id { get; set; }\n        public string Code { get; set; }\n        public string Password { get; set; }\n        public int? Gender { get; set; }\n        public string ImageUrl { get; set; }\n        public DateTime? Birthday { get; set; }\n        public string Email { get; set; }\n        public string Mobile { get; set; }\n        public string WeChatAccount { get; set; }\n        public string DingTalkAccount { get; set; }\n        public string DingTalkId { get; set; }\n        public string OfficePhone { get; set; }\n        public string QQ { get; set; }\n        public string Address { get; set; }\n        public int? IsAdministrator { get; set; }\n        public string Name { get; set; }\n        public string Description { get; set; }\n        public string UnitId { get; set; }\n        public DateTime? CreatedTime { get; set; }\n        public DateTime? ModifiedTime { get; set; }\n        public int? SortKey { get; set; }\n        public int? State { get; set; }\n    }\n}\n";
        }


    }
}

src/LJD.App.Web/Areas/Admin/Views/RapidDevelopment/BuildCode.cshtml
@{
    ViewData["Title"] = "BuildCode";
    Layout = "~/Views/Shared/_LayUIFormLayout.cshtml";
}


<div class="layui-form" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label">文件名</label>
        <div class="layui-input-block">
            <input type="text" name="fileName" lay-verify="required" placeholder="" autocomplete="off" class="layui-input" value="@ViewData["fileName"]">
        </div>
    </div>
    <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">代码</label>
        <div class="layui-input-block">
            <textarea placeholder="代码" class="layui-textarea" style="min-height: 500px">@ViewData["Code"]</textarea>
        </div>
    </div>
</div>

src/LJD.App.Web/Areas/Admin/Views/RapidDevelopment/Index.cshtml
@{
    ViewData["Title"] = "快速开发";
    Layout = "~/Views/Shared/_LayUILayout.cshtml";
}


<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label">标题</label>
                    <div class="layui-input-inline">
                        <input type="text" name="title" placeholder="请输入" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn  layuiadmin-btn-list " lay-submit lay-filter="LAY-app-search">
                        <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                    </button>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <label class="layui-form-label">生成代码：</label>
                <div class="layui-inline">
                    <button class="layui-btn layui-btn-radius layuiadmin-btn-list" data-type="createIRepository">IRepository代码</button>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layui-btn-radius layuiadmin-btn-list" data-type="createRepository">Repository代码</button>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layui-btn-radius layuiadmin-btn-list" data-type="createIService">IService代码</button>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layui-btn-radius layuiadmin-btn-list" data-type="createService">Service代码</button>
                </div>
            </div>
            <table id="LAY-app-list" lay-filter="LAY-app-list"></table>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        layui.use(['form', 'table'],
            function () {
                var table = layui.table
                    , form = layui.form;
                //Table定义
                table.render({
                    elem: '#LAY-app-list'
                    , url: '@Url.Action("List","RapidDevelopment")'  
                    ,request: {
                        pageName: 'pageIndex' //页码的参数名称，默认：page
                        ,limitName: 'pageSize' //每页数据量的参数名，默认：limit
                    }
                    , cols: [[
                        { type: 'radio'}
                        , { field: 'TableName', title: '表名',width:300  }
                        , { field: 'Description', title: '描述' ,minWidth:300 }
                    ]]
                    , page: true
                    , limit: 10
                    , limits: [10, 15, 20, 25, 30]
                });

                //监听工具条
                table.on('tool(LAY-app-list)',
                    function(obj) {
                        var data = obj.data;
                        if ("del" === obj.event) {
                            layer.confirm("确定删除此条评论？",
                                function(t) {
                                    //ajax删除
                                    //$.ajax({
                                    //    url: ''
                                    //    , type: 'POST'
                                    //    , data: { "id": data.Id}
                                    //    ,dataType: 'json'
                                    //    , success: function (data) {
                                    //        debugger
                                    //        if (data.Success) {
                                    //            obj.del();
                                    //        } else {
                                    //            layer.msg(data.msg);
                                    //        }
                                    //    }
                                    //});
                                    //表格删除
                                    obj.del();
                                    //关闭弹窗
                                    layer.close(t);
                                });
                        } else if ("edit" === obj.event) {
                            layer.msg("编辑");
                        }

                    });


                //监听搜索
                form.on('submit(LAY-app-search)', function (data) {
                    var field = data.field;

                    //执行重载
                    table.reload('LAY-app-list', {
                        where: field
                    });
                });

                var $ = layui.$, active = {
                    batchdel: function () {
                        var checkStatus = table.checkStatus('LAY-app-list')
                            , checkData = checkStatus.data; //得到选中的数据

                        if (checkData.length === 0) {
                            return layer.msg('请选择数据');
                        }

                        layer.confirm('确定删除吗？', function (index) {

                            //执行 Ajax 后重载
                            /*
                            admin.req({
                              url: 'xxx'
                              //,……
                            });
                            */
                            table.reload('LAY-app-list');
                            layer.msg('已删除');
                        });
                    },
                    createIRepository: function () {
                        var checkStatus = table.checkStatus('LAY-app-list'); //idTest 即为基础参数 id 对应的值
                        if (checkStatus.data.length !== 1) {
                            return layer.msg('请选择需要生成的表！', {icon: 5});
                        }
                        var data = checkStatus.data[0];
                        debugger
                        layer.open({
                            type: 2
                            , title: '生成IRepository'
                            , content: '@Url.Action("BuildCode","RapidDevelopment")?tableName=' + data.tableName+'&buildType=IRepository'
                            , maxmin: false
                            , area: ['100%', '100%']
                            , btn: ['确定']
                            , yes: function (index, layero) {
                                layer.close(index); //关闭弹层
                            }
                        });
                    },
                    createRepository: function () {
                        var checkStatus = table.checkStatus('LAY-app-list'); //idTest 即为基础参数 id 对应的值
                        if (checkStatus.data.length !== 1) {
                            return layer.msg('请选择需要生成的表！', {icon: 5});
                        }
                        var data = checkStatus.data[0];
                        debugger
                        layer.open({
                            type: 2
                            , title: '生成Repository'
                            , content: '@Url.Action("BuildCode","RapidDevelopment")?tableName=' + data.tableName+'&buildType=Repository'
                            , maxmin: false
                            , area: ['100%', '100%']
                            , btn: ['确定']
                            , yes: function (index, layero) {
                                layer.close(index); //关闭弹层
                            }
                        });
                    },
                    createIService: function () {
                        var checkStatus = table.checkStatus('LAY-app-list'); //idTest 即为基础参数 id 对应的值
                        if (checkStatus.data.length !== 1) {
                            return layer.msg('请选择需要生成的表！', {icon: 5});
                        }
                        var data = checkStatus.data[0];
                        debugger
                        layer.open({
                            type: 2
                            , title: '生成IService'
                            , content: '@Url.Action("BuildCode","RapidDevelopment")?tableName=' + data.tableName+'&buildType=IService'
                            , maxmin: false
                            , area: ['100%', '100%']
                            , btn: ['确定']
                            , yes: function (index, layero) {
                                layer.close(index); //关闭弹层
                            }
                        });
                    },
                    createService: function () {
                        var checkStatus = table.checkStatus('LAY-app-list'); //idTest 即为基础参数 id 对应的值
                        if (checkStatus.data.length !== 1) {
                            return layer.msg('请选择需要生成的表！', {icon: 5});
                        }
                        var data = checkStatus.data[0];
                        debugger
                        layer.open({
                            type: 2
                            , title: '生成Service'
                            , content: '@Url.Action("BuildCode","RapidDevelopment")?tableName=' + data.tableName+'&buildType=Service'
                            , maxmin: false
                            , area: ['100%', '100%']
                            , btn: ['确定']
                            , yes: function (index, layero) {
                                layer.close(index); //关闭弹层
                            }
                        });
                    },
                };

                $('.layui-btn.layuiadmin-btn-list').on('click', function () {
                    var type = $(this).data('type');
                    active[type] ? active[type].call(this) : '';
                });
            });

    </script>
}