src/LJD.App.Web/Areas/Admin/Controllers/FunctionController.cs
using System;
using System.Linq;
using System.Linq.Expressions;
using LJD.App.Model.DbModels;
using LJD.App.Repository.IUnitOfWork;
using LJD.App.Service;
using LJD.App.Service.IService;
using LJD.App.Util;
using LJD.App.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LJD.App.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FunctionController : BaseController
    {
        private readonly ISysFunctionService _sysFunctionService;
        private readonly IUnitOfWork _unitOfWork;

        public FunctionController(ISysFunctionService sysFunctionService, IUnitOfWork unitOfWork)
        {
            _sysFunctionService = sysFunctionService;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(string objectId)
        {
            ViewData["parentId"] = objectId;
            return View();
        }

        public IActionResult List(string parentId,string fName,string status, PagerInfo pagerInfo)
        {
            Expression<Func<SysFunction, bool>> whereExpression = f => f.ParentID.Equals(parentId);
            if (!string.IsNullOrEmpty(fName))
            {
                whereExpression = whereExpression.And(f => f.FName.Contains(fName));
            }

            if (!string.IsNullOrEmpty(status))
            {
                int state = Convert.ToInt32(status);
                whereExpression = whereExpression.And(f => f.Status.Equals(state));
            }
            var list = _sysFunctionService.GetList(pagerInfo.PageIndex, pagerInfo.PageSize, out var count, whereExpression, true, f => f.Sort).ToList();

            return Json(BuildSuccessTableResult(count, list));
        }

        public IActionResult Form(string objectId,string parentId)
        { 
            //如果objectId不为空的话 需要则是编辑，获取信息否则新建一个
            var sysFunction = string.IsNullOrEmpty(objectId) ? new SysFunction() {ParentID = parentId ,Status = (int)Status.On} : _sysFunctionService.GetList( f => f.ObjectID.Equals(objectId)).FirstOrDefault();

            return View(sysFunction);
        }

        [HttpPost]
        public IActionResult Form(SysFunction sysFunction)
        {
            ResponseResult responseResult = new ResponseResult(success: false, message: "保存失败！");
            if (string.IsNullOrEmpty(sysFunction.ObjectID))
            {
                sysFunction.CreatedBy = CurrentUserManage.UserInfo.URealName;
                sysFunction.CreatedTime = DateTime.Now;
                sysFunction.Status = sysFunction.Status == 0 ? 0 : 1;
                _sysFunctionService.Create(sysFunction);

                if (_unitOfWork.SaveChanges() == 1)
                {
                    responseResult.Success = true;
                    responseResult.Message = "保存成功！";
                }
            }
            else
            {
                var model = _sysFunctionService.GetList(f => f.ObjectID.Equals(sysFunction.ObjectID))
                    .FirstOrDefault();
                if (model != null)
                {

                    model.FName = sysFunction.FName;
                    model.FFunction = sysFunction.FFunction;
                    model.FURL = sysFunction.FURL;
                    model.FIcon = sysFunction.FIcon; 
                    model.Remark = sysFunction.Remark;
                    model.Sort = sysFunction.Sort;
                    //后台设置项
                    model.Status = sysFunction.Status == 0 ? 0 : 1;
                    model.ModifiedTime = DateTime.Now;
                    model.ModifiedBy = CurrentUserManage.UserInfo.URealName;
                    _sysFunctionService.Edit(model);


                    if (_unitOfWork.SaveChanges() == 1)
                    {
                        responseResult.Success = true;
                        responseResult.Message = "保存成功！";
                    }
                }
                else
                {
                    responseResult.Message = "要修改的数据不存在！";
                }
            }

            return Json(responseResult);

        }

        [HttpPost]
        public IActionResult Delete(string ids)
        {
            var idsList = ids.ToList<string>();
            _sysFunctionService.Delete(f => idsList.Contains(f.ObjectID));
            _unitOfWork.SaveChanges();
            return Json(new ResponseResult(true, "删除成功！"));

        }
    }
}

src/LJD.App.Web/Areas/Admin/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using LJD.App.Model.DbModels;
using LJD.App.Repository.IUnitOfWork;
using LJD.App.Service;
using LJD.App.Service.IService;
using LJD.App.Util; 
using LJD.App.Web.Controllers;
using Microsoft.AspNetCore.Mvc; 

namespace LJD.App.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenusController : BaseController
    {
        private readonly ISysMenusService _sysMenusService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ISysFunctionService _sysFunctionService;

        public MenusController(ISysMenusService sysMenusService, IUnitOfWork unitOfWork, ISysFunctionService sysFunctionService)
        {
            _sysMenusService = sysMenusService;
            _unitOfWork = unitOfWork;
            _sysFunctionService = sysFunctionService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(string status,string isLast, string isMenuShow, PagerInfo pagerInfo)
        {
            Expression<Func<SysMenus,bool>> whereExpression = m=>true;
            if (!string.IsNullOrEmpty(status))
            {
                int state = Convert.ToInt32(status);
                whereExpression = whereExpression.And(m => m.Status.Equals(state));
            }
            if (!string.IsNullOrEmpty(isLast))
            {
                int last = Convert.ToInt32(isLast);
                whereExpression = whereExpression.And(m => m.IsLast.Equals(last));
            }
            if (!string.IsNullOrEmpty(isMenuShow))
            {
                int menuShow = Convert.ToInt32(isMenuShow);
                whereExpression = whereExpression.And(m => m.IsMenuShow.Equals(menuShow));
            }

            var lists = _sysMenusService.GetList(whereExpression).OrderBy(m => m.Hierarchy).ThenBy(m=>m.Sort).ToList();

            return Json(BuildSuccessTableResult(lists.Count, lists));
        }

        public IActionResult Form(string objectId, string parentId = "0")
        { 
            //如果objectId不为空的话则是编辑，获取信息否则新建一个
            var sysMenus = string.IsNullOrEmpty(objectId) ? new SysMenus() { Status = (int)Status.On, ParentID = parentId, IsLast = parentId.Equals("0") ? (int)Status.Off : (int)Status.On,IsMenuShow = (int)Status.On } : _sysMenusService.GetList(m => m.ObjectID.Equals(objectId)).FirstOrDefault();

            return View(sysMenus);
        }

        [HttpPost]
        public IActionResult Form(SysMenus sysMenus)
        {
            ResponseResult responseResult = new ResponseResult(success: false, message: "保存失败！");
            try
            { 

                if (string.IsNullOrEmpty(sysMenus.ObjectID))
                {
                    #region 层级获取判断

                    int hierarchy = 1;
                    if (!sysMenus.ParentID.Equals("0"))
                    {
                        //搜索父节点的层级
                        int on = (int) Status.On;
                        var parentHierarchy = _sysMenusService.GetList(m => m.ObjectID.Equals(sysMenus.ParentID) && m.Status.Equals(on)).Select(m => m.Hierarchy).FirstOrDefault();
                        hierarchy = (int)(parentHierarchy + 1);
                    }
                    //判断当前层级是不是超过了最大层级限制
                    if (hierarchy > GlobalSwitch.MenuMaxHierarchy)
                    {
                        throw new Exception($"当前菜单已经超过系统设定菜单最大层级【{GlobalSwitch.MenuMaxHierarchy}】层，如需要继续添加请修改系统配置！");
                    } 
                    #endregion

                    sysMenus.ObjectID = Guid.NewGuid().ToString();
                    sysMenus.CreatedBy = CurrentUserManage.UserInfo.URealName;
                    sysMenus.CreatedTime = DateTime.Now;
                    sysMenus.IsLast = sysMenus.IsLast == 0 ? 0 : 1;
                    sysMenus.IsMenuShow = sysMenus.IsMenuShow == 0 ? 0 : 1;
                    sysMenus.Status = sysMenus.Status == 0 ? 0 : 1;
                    sysMenus.Hierarchy = hierarchy;
                    //末级菜单 默认创建 查询和管理权限项
                    if (sysMenus.IsLast == 0)
                    {
                        sysMenus.SysFunction = BuildFunctions(sysMenus.ObjectID,sysMenus.MArea,sysMenus.MController);
                    }
                    _sysMenusService.Create(sysMenus);
                    _unitOfWork.SaveChanges();
                    responseResult.Success = true;
                    responseResult.Message = "保存成功！";

                }
                else
                {
                    var model = _sysMenusService.GetList(m => m.ObjectID.Equals(sysMenus.ObjectID))
                        .FirstOrDefault();
                    if (model != null)
                    {

                        model.MName = sysMenus.MName; 
                        model.MArea = sysMenus.MArea;
                        model.MController = sysMenus.MController; 
                        model.MIcon = sysMenus.MIcon;
                        model.IsLast = sysMenus.IsLast == 0 ? 0 : 1;
                        model.IsMenuShow = sysMenus.IsMenuShow == 0 ? 0 : 1;
                        model.Remark = sysMenus.Remark;
                        model.ParentID = sysMenus.ParentID;
                        model.Sort = sysMenus.Sort;
                        //后台设置项
                        model.Status = sysMenus.Status == 0 ? 0 : 1;
                        model.ModifiedTime = DateTime.Now;
                        model.ModifiedBy = CurrentUserManage.UserInfo.URealName;
                        _sysMenusService.Edit(model);

                        if (_unitOfWork.SaveChanges() == 1)
                        {
                            responseResult.Success = true;
                            responseResult.Message = "保存成功！";
                        }
                    }
                    else
                    {
                        responseResult.Message = "要修改的数据不存在！";
                    }
                }
            }
            catch (Exception ex)
            {
                responseResult.Message = ex.Message;
            }

            return Json(responseResult);

        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            var result = _sysMenusService.Delete(id);
            return Json(result); 
        }
        #region 数据模型
        /// <summary>
        /// 创建末级菜单的时候，默认创建查询和管理两个权限项
        /// </summary>
        /// <param name="menuId">菜单ID</param>
        /// <returns></returns>
        public List<SysFunction> BuildFunctions(string menuId,string mArea,string mController)
        {
            return new List<SysFunction>()
            {
                new SysFunction()
                {
                    CreatedBy = CurrentUserManage.UserInfo.URealName,
                    CreatedTime = DateTime.Now,
                    FFunction = "Index",
                    FURL = $"/{mArea}/{mController}/Index",
                    FIcon = "fa fa-eye",
                    FName = "查看",
                    ParentID = menuId,
                    Remark = "查看权限",
                    Status = (int)Status.On,
                    Sort = 10
                },
                new SysFunction()
                {
                    CreatedBy = CurrentUserManage.UserInfo.URealName,
                    CreatedTime = DateTime.Now,
                    FFunction = "List",
                    FURL = $"/{mArea}/{mController}/List",
                    FIcon = "layui-icon layui-icon-search",
                    FName = "查询列表",
                    ParentID = menuId,
                    Remark = "查询列表",
                    Status = (int)Status.On,
                    Sort = 20
                },
                new SysFunction()
                {
                    CreatedBy = CurrentUserManage.UserInfo.URealName,
                    CreatedTime = DateTime.Now,
                    FFunction = "Form",
                    FURL = $"/{mArea}/{mController}/Form",
                    FIcon = "layui-icon layui-icon-search",
                    FName = "新增或编辑",
                    ParentID = menuId,
                    Remark = "新增或编辑",
                    Status = (int)Status.On,
                    Sort = 30
                },
                new SysFunction()
                {
                    CreatedBy = CurrentUserManage.UserInfo.URealName,
                    CreatedTime = DateTime.Now,
                    FFunction = "Delete",
                    FURL = $"/{mArea}/{mController}/Delete",
                    FIcon = "layui-icon layui-icon-delete",
                    FName = "删除",
                    ParentID = menuId,
                    Remark = "删除",
                    Status = (int)Status.On,
                    Sort = 40
                }
            };
        }


        #endregion

    }

}

src/LJD.App.Web/Areas/Admin/Views/Menus/Index.cshtml
@using LJD.App.Util
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayUILayout.cshtml";
}

<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">  
                <div class="layui-inline">
                    <label class="layui-form-label">状态</label>
                    <div class="layui-input-inline">
                        <select name="status">
                            <option value="">请选择</option>
                            <option value="0">启用</option>
                            <option value="1">禁用</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">末级</label>
                    <div class="layui-input-inline">
                        <select name="isLast">
                            <option value="">请选择</option>
                            <option value="0">是</option>
                            <option value="1">否</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">菜单显示</label>
                    <div class="layui-input-inline">
                        <select name="isMenuShow">
                            <option value="">请选择</option>
                            <option value="0">是</option>
                            <option value="1">否</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layuiadmin-btn-list" lay-submit lay-filter="LAY-app-search">
                        <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <button class="layui-btn layuiadmin-btn-list" data-type="add">添加菜单</button>
            </div>
            <table class="layui-hidden" id="treeTable" lay-filter="treeTable"></table>
            <script type="text/html" id="StatusTpl">
                {{# if(d.Status==0){ }}
                <button class="layui-btn layui-btn-xs">启用</button>
                {{# } else { }}
                <button class="layui-btn layui-btn-primary layui-btn-xs">禁用</button>
                {{# } }}
            </script>
            <script type="text/html" id="IsLastTpl">
                {{# if(d.IsLast==0){ }}
                <button class="layui-btn layui-btn-xs">是</button>
                {{# } else { }}
                <button class="layui-btn layui-btn-primary layui-btn-xs">否</button>
                {{# } }}
            </script>
            <script type="text/html" id="IsMenuShowTpl">
                {{# if(d.IsMenuShow==0){ }}
                <button class="layui-btn layui-btn-xs">是</button>
                {{# } else { }}
                <button class="layui-btn layui-btn-primary layui-btn-xs">否</button>
                {{# } }}
            </script>
            <script type="text/html" id="MIconTpl">
                <i class="{{d.MIcon}}"></i>
            </script>
            <script type="text/html" id="table-list">
                <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                <a class="layui-btn layui-bg-orange layui-btn-xs" lay-event="setBtn"><i class="layui-icon layui-icon-set"></i>权限项设置</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del"><i class="layui-icon layui-icon-delete"></i>删除</a>
            </script>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        var editObj=null,ptable=null,treeGrid=null,tableId='treeTable',layer=null;
    layui.use(['jquery', 'treeGrid', 'layer','util','form'], function () {
        var $ = layui.jquery ,util=layui.util, form = layui.form;
        treeGrid = layui.treeGrid;//很重要
        layer = layui.layer;
        ptable = treeGrid.render({
            id: tableId
            , elem: '#' + tableId
            ,idField:'ObjectID'//必須字段
            , url: '@Url.Action("List", "Menus")'
            , cellMinWidth: 100
            , treeId: 'ObjectID'//树形id字段名称
            , treeUpId: 'ParentID'//树形父id字段名称
            , treeShowName: 'MName'//以树形式显示的字段
            , iconOpen: true//是否显示图标【默认显示】
            , isOpenDefault: true//节点默认是展开还是折叠【默认展开】
            ,loading:true
            , method: 'get'
            ,request: {
                pageName: 'pageIndex' //页码的参数名称，默认：page
                ,limitName: 'pageSize' //每页数据量的参数名，默认：limit
            }
            ,isPage:false
            , cols: [[
                {type:'numbers'}
                ,{type:'radio'}
                //,{type:'checkbox'}
                ,{ field: 'MName', width: 200, title: '菜单名称',sort:true } 
                , { field: "MArea", title: "区域",width:100 }
                , { field: "MController", title: "控制器" }
                //, { field: "MAction", title: "方法" ,hide:true }
                 , { field: "MIcon", title: "图标", templet: "#MIconTpl",width:60, align: 'center' }
                , { field: "Remark", title: "备注" }
                //, { field: "ParentID", title: "父ID",hide:true }
                //, { field: "Sort", title: "排序值" ,hide:true}
                //通用项
                , { field: "CreatedTime", title: "创建时间", width: 100, templet: function (d) {return util.toDateString(d.CreatedTime,"yyyy-MM-dd")} , sort: !0 }
                , { field: "Status", title: "状态", templet: "#StatusTpl", width: 80, align: "center" }
                , { field: "IsLast", title: "末级", templet: "#IsLastTpl", width: 80, align: "center" }
                , { field: "IsMenuShow", title: "菜单显示", templet: "#IsMenuShowTpl", width: 150, align: "center" }
                //,{
                //    width: 100, title: '操作', align: 'center'/*toolbar: '#barDemo'*/
                //    , templet: function (d) {
                //        var html = '';
                //        var addBtn = '<a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="add">添加</a>';

                //        var delBtn = '<a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>';
                //        return addBtn + delBtn;
                //    }
                //}
                 , { title: "操作" , align: "center",  toolbar: "#table-list", width: 260 }
            ]]
            ,parseData:function (res) {//数据加载后回调
                return res;
            }
            ,onClickRow:function (index, o) {
                console.log(index,o,"单击！");
            }
            ,onDblClickRow:function (index, o) {
                console.log(index,o,"双击");
            }
            ,onCheck:function (obj,checked,isAll) {//复选事件
                console.log(obj,checked,isAll);
            }
            ,onRadio:function (obj) {//单选事件
                console.log(obj);
            }

        });
        //工具按钮
        treeGrid.on('tool('+tableId+')',function (obj) {
            if(obj.event === 'del'){//删除行
                del(obj);
            }else if(obj.event==="edit"){//添加行
                edit(obj);
            } else if (obj.event === "setBtn") {//按钮设置
                setBtn(obj);
            }
        });
        //监听搜索
        form.on('submit(LAY-app-search)', function (data) {
            var field = data.field;

            //执行重载
            treeGrid.query(tableId,{
                where:field
            });
        });

        function del(obj) {
            var data = obj.data;
            if (data.children.length !== 0) {
                layer.msg('存在下级菜单,不可删除！', {icon: 5});
            } else {
                layer.confirm("确定删除吗？", {icon: 3, title:'提示'},
                    function (index) {//确定回调
                        //关闭弹窗
                        layer.close(index);
                        $.ajax({
                            url: '@Url.Action("Delete", "Menus")',
                            type: 'POST',
                            data: { id:  data.ObjectID},
                            dataType: 'json',
                            success: function(data) {
                                debugger;
                                if (data.Success) {
                                    //表格删除
                                    obj.del();
                                } else {
                                    layer.msg(data.Message, {icon:5});
                                }
                            }
                        });
                    },function (index) {//取消回调
                        layer.close(index);
                    }
                );
            }
        }

        function edit(obj) {
            var data = obj.data;
            layer.open({
                    type: 2,
                    title: "编辑",
                    content: "@Url.Action("Form", "Menus")?objectId=" + data.ObjectID,
                    maxmin: !0,
                    area: ['60%', '95%'],
                    btn: ["确定", "取消"],
                    yes: function (e, i) {
                        var l = window["layui-layer-iframe" + e],
                            a = i.find("iframe").contents().find("#layuiadmin-app-form-edit");
                        l.layui.form.on("submit(layuiadmin-app-form-edit)",
                            function (i) {
                                debugger
                                //获取新开窗口的form
                                var field = i.field;
                                //提交 Ajax 成功后，关闭当前弹层并重载表格
                                $.ajax({
                                    url: '@Url.Action("Form", "Menus")',
                                    type: 'POST',
                                    data: field,
                                    dataType: 'json',
                                    success: function(data) {
                                        debugger;
                                        if (data.Success) {
                                            treeGrid.reload(tableId);
                                            //清空form
                                            form.render();
                                            //关闭弹窗
                                            layer.close(e);
                                        } else {
                                            layer.msg(data.Message, {icon: 5});
                                        }
                                    }
                                });
                            }), a.trigger("click");
                    }
                });
        }

        function setBtn(obj) {
            layer.open({
                type: 2,
                title: "【"+obj.data.MName+"】权限项设置",
                content: "@Url.Action("Index","Function")?objectId=" + obj.data.ObjectID,
                maxmin: !0,
                area: ['80%', '95%'],
                btn: ["确定", "关闭"],
                yes: function (e, i) {
                    //关闭窗口
                    layer.close(e);
                }
            });
        }

        function addChild(parentId) {
            layer.open({
                type: 2
                , title: '添加菜单'
                , content: '@Url.Action("Form","Menus")?parentId='+parentId
                , maxmin: true
                , area: ['60%', '95%']
                , btn: ['确定', '取消']
                , yes: function (index, layero) {
                    //点击确认触发 iframe 内容中的按钮提交
                    var submit = layero.find('iframe').contents().find("#layuiadmin-app-form-submit");
                    submit.click();
                }
            });
        }

        //顶部按钮
        var $ = layui.$, active = {
            add: function () {
                var data = treeGrid.radioStatus(tableId);
                debugger;
                if (!data.ObjectID) {
                    layer.confirm("确定添加根菜单吗？", {icon: 3, title:'提示'},
                        function (index) {//确定回调
                            //关闭弹窗
                            layer.close(index);
                            addChild('0');
                        }
                    );
                } else {
                    if (data.Hierarchy>=@GlobalSwitch.MenuMaxHierarchy) {
                       return  layer.alert('当前菜单已经是系统设定菜单最大层级【@GlobalSwitch.MenuMaxHierarchy】层，如需要继续添加请修改系统配置！', {icon: 5, title:'错误'});
                    }
                    if (data.IsLast===0) {
                        layer.msg('末级菜单不能添加子菜单！', {icon: 5});
                    } else {
                        return addChild(data.ObjectID);
                    }
                }

            }
        };

        $('.layui-btn.layuiadmin-btn-list').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });
    </script>
}